# Generated by Django 4.0 on 2021-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('issue_description', models.TextField(max_length=300)),
                ('serial', models.CharField(help_text='Example for a serial 24-X-125447-DC', max_length=64)),
                ('light_status1', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('BLINK', 'Blink')], default='OFF', max_length=5)),
                ('light_status2', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('BLINK', 'Blink')], default='OFF', max_length=5)),
                ('light_status3', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('BLINK', 'Blink')], default='OFF', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.CharField(default='n/a', max_length=20)),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'ordering': ['created_at'],
            },
        ),
    ]
